required = ["github.com/ovh/venom", "github.com/golang/lint/golint"]

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/loopfz/gadgeto"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "~1.9"

[[constraint]]
  name = "github.com/gin-gonic/contrib"
  branch = "master"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "~2.2"

[[constraint]]
  branch = "master"
  name = "github.com/juju/errors"

[[constraint]]
  branch = "master"
  name = "github.com/rubenv/sql-migrate"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "~1.10"

[[override]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/gzip"

[[constraint]]
  name = "github.com/fabienm/go-logrus-formatters"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/wI2L/fizz"
  version = "~0.10.2"

[[constraint]]
  name = "github.com/Selvatico/go-mocket"
  version = "~1.0.4"


[[constraint]]
  name = "github.com/gavv/httpexpect"
  branch = "v1"

[[override]]
  name = "github.com/valyala/fasthttp"
  branch = "master"
